//
//  KDSettingsWorker.swift
//  KitchenDisplay
//
//  Created by Wipro on 24/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class KDSettingsWorker
{
  func doSomeWork() -> [Settings]
  {
    var settingdata = [Settings]()
    if let path = Bundle.main.path(forResource: "settings", ofType: "json") {
        do {
            let fileUrl = URL(fileURLWithPath: path)
            // Getting data from JSON file using the file URL
            let data = try Data(contentsOf: fileUrl, options: .mappedIfSafe)
            let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
            print(json as Any)
            let user = try? JSONDecoder().decode(Settings.self, from: data)
            
            print(user?.title ?? "")
            print(user?.heading ?? "")
            settingdata = [user] as! [Settings]
            
        } catch {
            print(error.localizedDescription)
        }
    }
    return settingdata
    
    }
}
