//
//  KDSettingsModels.swift
//  KitchenDisplay
//
//  Created by Wipro on 24/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum KDSettings
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        
    }
    struct Response
    {
        var settings: [Settings]
        
    }
    struct ViewModel
    {
        struct DisplayedOrder
        {
            var elapsed_time_alert_blue: String
            var elapsed_time_alert_yellow: String
            var elapsed_time_alert_red: String
            var kitchen_printer_filtering: String
            var title: String
            var lbl1: String
            var lbl2: String
            var heading: String
        }
        var displayedOrders: [DisplayedOrder]

    }
  }
}
