//
//  KDSettingsPresenter.swift
//  KDSkeletonPOC
//
//  Created by Wipro on 24/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol KDSettingsPresentationLogic
{
  func presentSomething(response: KDSettings.Something.Response)
}

class KDSettingsPresenter: KDSettingsPresentationLogic
{
  weak var viewController: KDSettingsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: KDSettings.Something.Response)
  {
    var displayedOrders: [KDSettings.Something.ViewModel.DisplayedOrder] = []
    for order in response.settings {
        
        let displayedOrder = KDSettings.Something.ViewModel.DisplayedOrder(elapsed_time_alert_blue: order.elapsed_time_alert_blue, elapsed_time_alert_yellow: order.elapsed_time_alert_yellow, elapsed_time_alert_red: order.elapsed_time_alert_red, kitchen_printer_filtering: order.kitchen_printer_filtering, title: order.title, lbl1: order.lbl1, lbl2: order.lbl2, heading: order.heading)
        displayedOrders.append(displayedOrder)
    }
    let viewModel = KDSettings.Something.ViewModel(displayedOrders: displayedOrders)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
